version: 2.1
orbs:
  k8s: circleci/kubernetes@0.7.0
  s3: circleci/aws-s3@1.0.13
commands:
  git_checkout_from_cache:
    description: "Git checkout and save cache"
    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-
      - run: 
          name: Fetch git tags 
          command: |
            mkdir -p ~/.ssh
            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ== ' >> ~/.ssh/known_hosts
            # Fetch tags if git cache is present
            if [ -e /home/circleci/project/.git ]
            then
              git fetch origin --tags
            fi
      - checkout
      - run:
          name: Compress git objects 
          command: git gc
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
  npm_install_from_cache:
    description: "npm install and save cache"
    steps:
      - restore_cache:
          keys:
            - node-{{ checksum "package-lock.json" }}
            - node-
      - run:
          name: Install npm packages
          command: npm ci
      - save_cache:
          key: node-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
  npm_test:
    description: "Run npm test"
    steps:
      - run:
          name: "Run test"
          command: npm test
  build:
    description: "Build"
    steps:
      - run:
          name: "Run build"
          command: npm run build
  compress:
    description: "Compress"
    steps:
      - run:
          name: "Compress"
          command: |
            pushd public/
            tar -cvf artifact.tar *
            mv artifact.tar ${OLDPWD}/
      - run:
          name: "Tag commit id as artifact identifer"
          command: echo "${CIRCLE_TAG}" > artifact-info.txt
  upload_artifact:
    description: "upload build artifact to s3 bucket"
    steps:
      - s3/copy:
          from: artifact.tar
          to: 's3://${CONTEXT_ARTIFACT_S3_BUCKET}/${CIRCLE_PROJECT_REPONAME}/'
          aws-access-key-id: env_CONTEXT_ARTIFACT_S3_AWS_ACCESS_KEY_ID
          aws-secret-access-key: env_CONTEXT_ARTIFACT_S3_AWS_SECRET_ACCESS_KEY
          aws-region: env_CONTEXT_ARTIFACT_S3_AWS_REGION
          arguments: '--metadata "{\"x-amz-artifact-id\": \"${CIRCLE_TAG}\" }"'
  upload_checksum:
    description: "upload artifact checksum to s3"
    steps:
      - s3/copy:
          from: artifact-info.txt
          to: 's3://${CONTEXT_ARTIFACT_S3_BUCKET}/${CIRCLE_PROJECT_REPONAME}/'
          aws-access-key-id: env_CONTEXT_ARTIFACT_S3_AWS_ACCESS_KEY_ID
          aws-secret-access-key: env_CONTEXT_ARTIFACT_S3_AWS_SECRET_ACCESS_KEY
          aws-region: env_CONTEXT_ARTIFACT_S3_AWS_REGION
  docker_build:
    description: "Build Docker image"
    steps:
      - setup_remote_docker
      - run: 
          name: Building docker image
          command: |
            docker build -t ${DOCKHUB_ORGANISATION}/deriv-com:${CIRCLE_TAG:-latest} .
  docker_push:
    description: "Push image to docker hub"
    steps:
      - run: 
          name: Pushing Image to docker hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push ${DOCKHUB_ORGANISATION}/deriv-com:${CIRCLE_TAG:-latest}
  k8s_deploy:
    description: "Deploy to k8s cluster"
    parameters:
      k8s_svc_name:
        type: string
        default: "staging-deriv-com"
    steps:
      - k8s/install-kubectl
      - run: 
          name: Deploying to k8s cluster for service << parameters.k8s_svc_name >>
          command: |
            echo $CA_CRT | base64 --decode > ca.crt
            kubectl --server=${KUBE_SERVER} --certificate-authority=ca.crt --token=$SERVICEACCOUNT_TOKEN set image deployment/<< parameters.k8s_svc_name >> << parameters.k8s_svc_name >>=${DOCKHUB_ORGANISATION}/deriv-com:${CIRCLE_TAG}
jobs:
  test:
    docker:
      - image: circleci/node:lts-stretch
        environment:
          #- NODE_OPTIONS=--max_old_space_size=4096
          - GATSBY_CPU_COUNT=2
    steps:
      - git_checkout_from_cache
      - npm_install_from_cache
      - npm_test
      - build
      - compress
      - upload_artifact  # uploading the built code to s3 to create a backup of key services separate from Kubernetes deployment
      - upload_checksum  # uploading compressed artifact checksum to cross match artifact fingerprint
      - docker_build
      - docker_push
      - k8s_deploy
  release:
    docker:
      - image: circleci/node:lts-stretch
        environment:
          - NODE_OPTIONS=--max_old_space_size=4096
          - GATSBY_CPU_COUNT=2
    steps:
      - git_checkout_from_cache
      - npm_install_from_cache
      - build
      - compress
      - upload_artifact  # uploading the built code to s3 to create a backup of key services separate from Kubernetes deployment
      - upload_checksum  # uploading compressed artifact checksum to cross match artifact fingerprint
      - docker_build
      - docker_push
      - k8s_deploy
      
workflows:
  build_and_push_test:
    jobs:
      - test:
          context: binary-frontend-deploy  # using context to retrieve shared secret from circle ci
  build_and_push_dev:
    jobs:
      - test:
          filters:
            branches:
              only: /^dev/
          context: binary-frontend-artifact-upload  # using context to retrieve shared secret from circle ci
  build_and_push_master:
    jobs:
      - release:
          filters:
            branches:
              only: /^master/
          context: binary-frontend-artifact-upload  # using context to retrieve shared secret from circle ci